services:
	db:
		image: mysql
		ports:
			-"3306:3306"
		environment:
			MYSQL_ROOT_PASSWORD: pass123
			MYSQL_USER: root
	phpmyadmin:
		image: phpmyadmin/phpmyadmin
		restart: always
		environment:
			- PMA_ARBITRARY=1
		ports:
			- 8082:80
			
